-- The LIKE operator in SQL filters rows based on a specific string pattern rather than an exact match.
-- THE Wildcard (%) IS USED FOR IT
SELECT NAME FROM STUDENT WHERE NAME LIKE 'A%'; -- IT IS START WITH VALUE IT PRINT ALL THE NAMES OF STUDENT WHOSE NAME STARTS WITH A
SELECT NAME, MAIL FROM STUDENT WHERE MAIL LIKE '%@gmail.com' ; -- IT IS ENDS WITH VALUE IT PRINT ALL THE NAMES,MAILS OF STUDENT WHOSE MAIL IS GIVEN PROPERLY
SELECT NAME FROM STUDENT WHERE NAME LIKE '%H%'; -- IT IS Contains Anywhere VALUE IT PRINT ALL THE NAMES OF STUDENT WHOSE NAME CONTAINS H
