-- LIMIT is used to limit the selecting data for the requried limit
-- The syntax is SELECT COLUMN_NAAME FROM TABLE_NAME WHERE CONDITION1 ORDER BY COLUMN_NAME ASC/DESC LIMT=1;
SELECT NAME,AGE FROM STUDENT ORDER BY AGE DESC LIMIT 2; -- PRINTS THE TOP TWO OLDEST STUDENTS 
SELECT NAME,AGE FROM STUDENT ORDER BY AGE ASC LIMIT 2; -- PRINTS THE TOP TWO YOUNGER STUDENTS STUDENTS 
