-- ORDER IS USED TO SHOW DATA IN A ASCENDING OR DESCINDING ORDER
-- THE SYNTAX FOR IT IS ORDER BY COLUMN_NAME ASC FOR ASCENDING ORDER DESC FOR DESCINDING ORDER
SELECT NAME FROM STUDENT WHERE AGE>20 ORDER BY AGE DESC; -- FOR GETTING AGE OF STUDENT WITH HIGH AGE TO LOW AGE
SELECT NAME,AGE FROM STUDENT WHERE AGE>20 ORDER BY AGE ASC; -- FOR GETTING AGE OF STUDENT WITH LOW AGE TO HIGH AGE
