-- This shows how to insert / create data into a table
-- INSERT command is used to add data into a table
 INSERT INTO STUDENT (NAME,AGE,ROLLNO) VALUES ('HARI',19,'xxxxxxxxx'); -- TO add single value into a table
--TO ADD Multiple Rows at a time can be done in two ways
--1ST WAY:
 INSERT ALL
   INTO STUDENT (NAME,AGE,ROLLNO) VALUES ('DHARAK',21,'23XX1A1248')
   INTO STUDENT (NAME,AGE,ROLLNO) VALUES ('CHILAKA',20,'23XX1A1243')
   INTO STUDENT (NAME,AGE,ROLLNO) VALUES ('RAM',21,'23XX1A1242')
   SELECT * FROM DUAL;

--2ND WAY
 INSERT INTO STUDENT (NAME,AGE,ROLLNO)
   SELECT 'LASH', 21,'23XX1A1241'FROM DUAL UNION ALL
   SELECT 'RAFI', 23,'23XX1A1251'FROM DUAL UNION ALL
   SELECT 'PAUL', 21,'24XX5A1204'FROM DUAL;
