-- UPDATE COMMAND IS USED TO UPDATE DATA PRESENT IN THE CURRENT TABLE
-- SET IS USED IN IT
-- THE SYNTAX IS UPDATE TABLE-NAME SET CLOUMN=NEW_DATA WHERE DATA
UPDATE STUDENT SET AGE=20 WHERE NAME='HARI';
