-- THE COUNT IS USED TO CHECK HOW MANY ROWS ROWS ARE PRESENT IN A TABEL 
-- THE SYNTAX FOR IT IS SELECT COUNT(*) FROM TABLE_NAME;
-- IT ALSO COUNT  ROWS WITH NULL VALUES
SELECT COUNT(*) FROM STUDENT;
